apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_DB: cG9zdGdyZXNkYg==
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: JVR0c2B6U3o5YDVbRU1wNQ==
  POSTGRES_HOST: L2Nsb3Vkc3FsL2F0bGFudGVhbi13YXJlcy00MjY5MjEtajM6dXMtY2VudHJhbDE6Y2ktY2QtZGVtby1kYi1zdGFnaW5n
  